/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HealthpassResultsRouteImport } from './routes/healthpass-results'
import { Route as HealthSummaryRouteImport } from './routes/health-summary'
import { Route as GenerateHealthpassRouteImport } from './routes/generate-healthpass'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AppointmentSelectionRouteImport } from './routes/appointment-selection'
import { Route as IndexRouteImport } from './routes/index'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthpassResultsRoute = HealthpassResultsRouteImport.update({
  id: '/healthpass-results',
  path: '/healthpass-results',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthSummaryRoute = HealthSummaryRouteImport.update({
  id: '/health-summary',
  path: '/health-summary',
  getParentRoute: () => rootRouteImport,
} as any)
const GenerateHealthpassRoute = GenerateHealthpassRouteImport.update({
  id: '/generate-healthpass',
  path: '/generate-healthpass',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AppointmentSelectionRoute = AppointmentSelectionRouteImport.update({
  id: '/appointment-selection',
  path: '/appointment-selection',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/appointment-selection': typeof AppointmentSelectionRoute
  '/dashboard': typeof DashboardRoute
  '/generate-healthpass': typeof GenerateHealthpassRoute
  '/health-summary': typeof HealthSummaryRoute
  '/healthpass-results': typeof HealthpassResultsRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/appointment-selection': typeof AppointmentSelectionRoute
  '/dashboard': typeof DashboardRoute
  '/generate-healthpass': typeof GenerateHealthpassRoute
  '/health-summary': typeof HealthSummaryRoute
  '/healthpass-results': typeof HealthpassResultsRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/appointment-selection': typeof AppointmentSelectionRoute
  '/dashboard': typeof DashboardRoute
  '/generate-healthpass': typeof GenerateHealthpassRoute
  '/health-summary': typeof HealthSummaryRoute
  '/healthpass-results': typeof HealthpassResultsRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/appointment-selection'
    | '/dashboard'
    | '/generate-healthpass'
    | '/health-summary'
    | '/healthpass-results'
    | '/login'
    | '/onboarding'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/appointment-selection'
    | '/dashboard'
    | '/generate-healthpass'
    | '/health-summary'
    | '/healthpass-results'
    | '/login'
    | '/onboarding'
  id:
    | '__root__'
    | '/'
    | '/appointment-selection'
    | '/dashboard'
    | '/generate-healthpass'
    | '/health-summary'
    | '/healthpass-results'
    | '/login'
    | '/onboarding'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppointmentSelectionRoute: typeof AppointmentSelectionRoute
  DashboardRoute: typeof DashboardRoute
  GenerateHealthpassRoute: typeof GenerateHealthpassRoute
  HealthSummaryRoute: typeof HealthSummaryRoute
  HealthpassResultsRoute: typeof HealthpassResultsRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/healthpass-results': {
      id: '/healthpass-results'
      path: '/healthpass-results'
      fullPath: '/healthpass-results'
      preLoaderRoute: typeof HealthpassResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health-summary': {
      id: '/health-summary'
      path: '/health-summary'
      fullPath: '/health-summary'
      preLoaderRoute: typeof HealthSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generate-healthpass': {
      id: '/generate-healthpass'
      path: '/generate-healthpass'
      fullPath: '/generate-healthpass'
      preLoaderRoute: typeof GenerateHealthpassRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointment-selection': {
      id: '/appointment-selection'
      path: '/appointment-selection'
      fullPath: '/appointment-selection'
      preLoaderRoute: typeof AppointmentSelectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppointmentSelectionRoute: AppointmentSelectionRoute,
  DashboardRoute: DashboardRoute,
  GenerateHealthpassRoute: GenerateHealthpassRoute,
  HealthSummaryRoute: HealthSummaryRoute,
  HealthpassResultsRoute: HealthpassResultsRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
